"""
Script para poblar MongoDB Atlas con datos de ejemplo del torneo ¿Y si, si? 2027.
Ejecuta:  python seed_data.py
"""
import random
from datetime import datetime, timedelta
from pymongo import MongoClient
from config import Config

client = MongoClient(Config.MONGO_URI)
db = client[Config.DB_NAME]

for coleccion in ["equipos", "jugadores", "partidos", "noticias", "eliminatorias", "boletos"]:
    db[coleccion].delete_many({})

EQUIPOS_DATA = [
    ("Argentina", "ar", "Sudamérica", "Monumental de Buenos Aires", "La Albiceleste", "CONMEBOL", 3, "Campeón (1978, 1986, 2022)",
     "Una de las selecciones más laureadas de la historia. Con Diego Maradona y Lionel Messi como sus máximos referentes, Argentina conquistó su tercera estrella en Qatar 2022 tras una final épica ante Francia."),
    ("Brasil", "br", "Sudamérica", "Maracaná", "La Canarinha", "CONMEBOL", 5, "Campeón (1958, 1962, 1970, 1994, 2002)",
     "El máximo ganador de Copas del Mundo y el único país que ha disputado todas las ediciones del torneo. Cuna de Pelé, Ronaldo y Ronaldinho, es sinónimo de fútbol ofensivo y espectáculo."),
    ("Francia", "fr", "Europa", "Stade de France", "Les Bleus", "UEFA", 2, "Campeón (1998, 2018)",
     "Ganó su primera estrella como anfitriona en 1998 y repitió el título veinte años después en Rusia 2018. Con Mbappé como su gran estandarte, es una de las potencias más temidas del fútbol actual."),
    ("Alemania", "de", "Europa", "Allianz Arena", "Die Mannschaft", "UEFA", 4, "Campeón (1954, 1974, 1990, 2014)",
     "Reconocida por su disciplina táctica y su capacidad de reinventarse. El título de Brasil 2014, con aquel histórico 7-1 a Brasil en semifinales, quedó grabado en la memoria del fútbol mundial."),
    ("España", "es", "Europa", "Santiago Bernabéu", "La Roja", "UEFA", 1, "Campeón (2010)",
     "Su generación dorada, liderada por Xavi e Iniesta, dominó el fútbol mundial entre 2008 y 2012 con el llamado 'tiki-taka', coronándose campeona del mundo en Sudáfrica 2010."),
    ("Inglaterra", "gb-eng", "Europa", "Wembley", "The Three Lions", "UEFA", 1, "Campeón (1966)",
     "Cuna del fútbol moderno. Ganó su único título como anfitriona en 1966 y desde entonces ha buscado repetir la hazaña, llegando cerca en varias ocasiones con generaciones talentosas."),
    ("México", "mx", "Norteamérica", "Estadio Azteca", "El Tri", "CONCACAF", 0, "Cuartos de final (1970, 1986)",
     "Selección histórica de la región, ha sido sede de dos Copas del Mundo (1970 y 1986). Su hinchada es reconocida como una de las más apasionadas del planeta."),
    ("Estados Unidos", "us", "Norteamérica", "MetLife Stadium", "The Stars and Stripes", "CONCACAF", 0, "Semifinal (1930)",
     "El fútbol crece con fuerza en Estados Unidos, que será uno de los anfitriones del Mundial 2026. Cuenta con una generación joven que juega en las mejores ligas de Europa."),
    ("Italia", "it", "Europa", "Estadio San Siro", "Gli Azzurri", "UEFA", 4, "Campeón (1934, 1938, 1982, 2006)",
     "Conocida por su histórica solidez defensiva (el 'catenaccio'), Italia es una de las selecciones más ganadoras del mundo, con su último título logrado en Alemania 2006."),
    ("Portugal", "pt", "Europa", "Estádio da Luz", "A Seleção das Quinas", "UEFA", 0, "Tercer lugar (1966)",
     "Con Cristiano Ronaldo como su máxima figura histórica, Portugal se consagró campeón de la Eurocopa 2016 y busca desde hace años levantar su primera Copa del Mundo."),
    ("Países Bajos", "nl", "Europa", "Johan Cruyff Arena", "Oranje", "UEFA", 0, "Subcampeón (1974, 1978, 2010)",
     "Inventora del 'fútbol total' de la mano de Johan Cruyff, ha llegado a tres finales de Copa del Mundo sin poder levantar el trofeo, siendo una de las grandes 'víctimas' de la historia del torneo."),
    ("Bélgica", "be", "Europa", "Estadio Rey Balduino", "Los Diablos Rojos", "UEFA", 0, "Tercer lugar (2018)",
     "Con una 'generación dorada' que incluyó a De Bruyne, Hazard y Lukaku, Bélgica alcanzó su mejor actuación histórica al terminar tercera en Rusia 2018."),
    ("Croacia", "hr", "Europa", "Estadio Poljud", "Vatreni", "UEFA", 0, "Subcampeón (2018)",
     "Una de las mayores sorpresas de la historia reciente: con apenas cuatro millones de habitantes, Croacia llegó a la final del Mundial 2018 liderada por Luka Modrić."),
    ("Uruguay", "uy", "Sudamérica", "Estadio Centenario", "La Celeste", "CONMEBOL", 2, "Campeón (1930, 1950)",
     "Campeona del primer Mundial de la historia en 1930 y protagonista del histórico 'Maracanazo' en 1950. Un gigante del fútbol sudamericano pese a su tamaño."),
    ("Colombia", "co", "Sudamérica", "Estadio Metropolitano", "Los Cafeteros", "CONMEBOL", 0, "Cuartos de final (2014)",
     "Su mejor Mundial fue Brasil 2014, donde James Rodríguez terminó como máximo goleador del torneo. Un fútbol vistoso y ofensivo caracteriza a esta selección."),
    ("Chile", "cl", "Sudamérica", "Estadio Nacional de Chile", "La Roja", "CONMEBOL", 0, "Tercer lugar (1962)",
     "Anfitriona y tercera en el Mundial de 1962, vivió su época dorada reciente al ganar dos Copas América consecutivas (2015 y 2016) con figuras como Alexis Sánchez y Arturo Vidal."),
    ("Japón", "jp", "Asia", "Estadio Nacional de Japón", "Samurai Blue", "AFC", 0, "Octavos de final (2002, 2010, 2018, 2022)",
     "La selección más constante de Asia en los últimos Mundiales, conocida por derrotar a potencias como Alemania y España en la fase de grupos de Qatar 2022."),
    ("Corea del Sur", "kr", "Asia", "Estadio de Seúl", "Taeguk Warriors", "AFC", 0, "Cuarto lugar (2002)",
     "Coanfitriona del Mundial 2002, logró un histórico cuarto lugar en esa edición. Son Heung-min, su capitán, es una de las grandes estrellas asiáticas del fútbol europeo."),
    ("Marruecos", "ma", "África", "Estadio Mohammed V", "Los Leones del Atlas", "CAF", 0, "Cuarto lugar (2022)",
     "Escribió historia en Qatar 2022 al convertirse en la primera selección africana en llegar a semifinales de un Mundial, eliminando en el camino a España y Portugal."),
    ("Senegal", "sn", "África", "Estadio Abdoulaye Wade", "Los Leones de la Teranga", "CAF", 0, "Cuartos de final (2002)",
     "Campeona de la Copa Africana de Naciones 2021, Senegal sorprendió al mundo llegando a cuartos de final en su debut mundialista en 2002, venciendo a la vigente campeona Francia."),
    ("Nigeria", "ng", "África", "Estadio Nacional Teslim Balogun", "Las Súper Águilas", "CAF", 0, "Octavos de final (1994, 1998, 2014)",
     "Una de las potencias históricas de África, con una gran cantera de talento que exporta jugadores a las principales ligas europeas cada temporada."),
    ("Ghana", "gh", "África", "Estadio de Accra", "Las Estrellas Negras", "CAF", 0, "Cuartos de final (2010)",
     "Estuvo a un penal de convertirse en la primera selección africana en semifinales de un Mundial en Sudáfrica 2010, en un partido que quedó marcado por la mano de Luis Suárez."),
    ("Canadá", "ca", "Norteamérica", "BMO Field", "Los Rojos", "CONCACAF", 0, "Fase de grupos (2022)",
     "Clasificó de forma invicta al Mundial de Qatar 2022 con una generación liderada por Alphonso Davies. Coanfitriona del Mundial 2026 junto a Estados Unidos y México."),
    ("Costa Rica", "cr", "Norteamérica", "Estadio Nacional de Costa Rica", "La Sele", "CONCACAF", 0, "Cuartos de final (2014)",
     "Protagonizó una de las mayores sorpresas de Brasil 2014 al terminar primera en un grupo con Uruguay, Italia e Inglaterra, llegando hasta cuartos de final."),
    ("Ecuador", "ec", "Sudamérica", "Estadio Monumental de Guayaquil", "La Tri", "CONMEBOL", 0, "Octavos de final (2006)",
     "Ha logrado clasificar a varias Copas del Mundo pese a jugar de local en altura extrema en Quito, lo que representa una gran ventaja competitiva regional."),
    ("Perú", "pe", "Sudamérica", "Estadio Nacional de Lima", "La Blanquirroja", "CONMEBOL", 0, "Cuartos de final (1970, 1978)",
     "Alcanzó cuartos de final en dos ocasiones durante los años setenta, una de las mejores épocas históricas del fútbol peruano."),
    ("Paraguay", "py", "Sudamérica", "Estadio Defensores del Chaco", "La Albirroja", "CONMEBOL", 0, "Octavos de final (2010)",
     "Su mejor actuación mundialista fue en Sudáfrica 2010, donde llegó hasta cuartos de final tras una destacada fase de grupos."),
    ("Arabia Saudita", "sa", "Asia", "Estadio Rey Fahd", "Los Halcones Verdes", "AFC", 0, "Octavos de final (1994)",
     "Protagonizó una de las mayores sorpresas en la historia reciente de los Mundiales al vencer a Argentina en el debut de Qatar 2022."),
    ("Qatar", "qa", "Asia", "Estadio Lusail", "Los Granates", "AFC", 0, "Fase de grupos (2022)",
     "Anfitriona del Mundial 2022, fue la primera selección sede en no superar la fase de grupos, pero ganó experiencia internacional valiosa para el futuro."),
    ("Australia", "au", "Oceanía", "Stadium Australia", "Los Socceroos", "AFC", 0, "Octavos de final (2006, 2022)",
     "Cambió de confederación de la OFC a la AFC en 2006 para enfrentar competencia más fuerte, logrando desde entonces clasificaciones más constantes a Copas del Mundo."),
    ("Dinamarca", "dk", "Europa", "Parken Stadium", "Los Daneses Dinamita", "UEFA", 0, "Cuartos de final (1998)",
     "Ganadora sorpresa de la Eurocopa 1992, mantiene una tradición de fútbol técnico y ofensivo con figuras destacadas como Christian Eriksen."),
    ("Polonia", "pl", "Europa", "Estadio Nacional de Varsovia", "Los Águilas Blancas", "UEFA", 0, "Tercer lugar (1974, 1982)",
     "Su época dorada llegó en los años setenta y ochenta con dos terceros lugares mundialistas. Hoy Robert Lewandowski, uno de los mejores goleadores de su generación, es su gran estandarte."),
]

equipos = []
for nombre, codigo, origen, estadio, apodo, confederacion, titulos, mejor_resultado, historia in EQUIPOS_DATA:
    equipos.append({
        "nombre": nombre, "bandera": "🏳️", "codigo_pais": codigo, "origen": origen,
        "estadio": estadio, "apodo": apodo, "confederacion": confederacion,
        "titulos_mundiales": titulos, "mejor_resultado": mejor_resultado, "historia": historia,
        "plantilla_actual": f"Posesión promedio {random.randint(48, 62)}%",
    })

ids_equipos = db.equipos.insert_many(equipos).inserted_ids
mapa_equipos = {e["nombre"]: idx for e, idx in zip(equipos, ids_equipos)}
estadio_a_pais = {e["estadio"]: e["nombre"] for e in equipos}

EQUIPOS_NOMBRES_ORDEN = [e[0] for e in EQUIPOS_DATA]
grupos = [EQUIPOS_NOMBRES_ORDEN[i:i + 4] for i in range(0, 32, 4)]

# (nombre, posicion, numero, goles en el torneo, dato relevante)
JUGADORES_DATA = {
    "Argentina": [
        ("Lionel Messi", "Delantero", 10, 6, "Ganador del Balón de Oro en 8 ocasiones, campeón del mundo en 2022."),
        ("Julián Álvarez", "Delantero", 9, 4, "Pieza clave del ataque argentino desde el título de Qatar 2022."),
        ("Emiliano Martínez", "Portero", 23, 0, "Elegido mejor portero del Mundial 2022 (Guante de Oro)."),
        ("Rodrigo De Paul", "Mediocampista", 7, 1, "Motor del mediocampo albiceleste, gran despliegue físico."),
        ("Nicolás Otamendi", "Defensa", 19, 0, "Central de experiencia y liderazgo en la zaga argentina."),
        ("Franco Armani", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Lisandro Martínez", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Cristian Romero", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Nicolás Tagliafico", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Leandro Paredes", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Enzo Fernández", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Ángel Di María", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Alexis Mac Allister", "Mediocampista", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Brasil": [
        ("Vinícius Jr.", "Delantero", 7, 5, "Uno de los extremos más veloces y desequilibrantes del fútbol actual."),
        ("Neymar", "Delantero", 11, 3, "Máximo goleador histórico de la selección brasileña."),
        ("Rodrygo", "Delantero", 19, 2, "Formado en la cantera del Santos, club histórico de Pelé."),
        ("Alisson Becker", "Portero", 1, 0, "Considerado uno de los mejores porteros del mundo en su posición."),
        ("Éder Militão", "Defensa", 3, 0, "Central de gran velocidad y salida limpia con el balón."),
        ("Ederson", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Marquinhos", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Danilo", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Bruno Guimarães", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Casemiro", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Lucas Paquetá", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Raphinha", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Endrick", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Francia": [
        ("Kylian Mbappé", "Delantero", 9, 7, "Campeón del mundo en 2018 con solo 19 años; hat-trick en la final de 2022."),
        ("Antoine Griezmann", "Mediocampista", 7, 2, "Pieza clave tanto en ataque como en la generación de juego."),
        ("Ousmane Dembélé", "Delantero", 10, 3, "Extremo veloz con gran capacidad de desborde por las bandas."),
        ("Aurélien Tchouaméni", "Mediocampista", 8, 0, "Mediocampista contenedor, pilar defensivo del equipo galo."),
        ("Mike Maignan", "Portero", 1, 0, "Portero titular, referente de la portería francesa."),
        ("Mike Maignan", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Théo Hernández", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("William Saliba", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Ibrahima Konaté", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Eduardo Camavinga", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("N'Golo Kanté", "Mediocampista", 11, 0, "Convocado a la selección para este torneo."),
        ("Randal Kolo Muani", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Marcus Thuram", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Alemania": [
        ("Jamal Musiala", "Mediocampista", 10, 3, "Una de las mayores promesas del fútbol alemán de las últimas décadas."),
        ("Kai Havertz", "Delantero", 29, 2, "Delantero versátil, capaz de jugar en varias posiciones de ataque."),
        ("Florian Wirtz", "Mediocampista", 17, 4, "Considerado un talento generacional del fútbol germano."),
        ("Manuel Neuer", "Portero", 1, 0, "Uno de los porteros más influyentes en la historia del fútbol alemán."),
        ("İlkay Gündoğan", "Mediocampista", 21, 1, "Capitán con amplia experiencia en el mediocampo europeo."),
        ("Marc-André ter Stegen", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Antonio Rüdiger", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Jonathan Tah", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Joshua Kimmich", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Robert Andrich", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Leroy Sané", "Delantero", 7, 0, "Convocado a la selección para este torneo."),
        ("Serge Gnabry", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Niclas Füllkrug", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
    ],
    "España": [
        ("Pedri", "Mediocampista", 8, 2, "Debutó como profesional a los 17 años, referente del mediocampo español."),
        ("Lamine Yamal", "Delantero", 19, 5, "El goleador más joven en la historia de una Eurocopa."),
        ("Rodri", "Mediocampista", 16, 1, "Ganador del Balón de Oro por su papel como mediocampista defensivo."),
        ("Unai Simón", "Portero", 23, 0, "Portero titular de la selección desde la Eurocopa 2021."),
        ("Dani Carvajal", "Defensa", 2, 0, "Lateral derecho de gran experiencia internacional."),
        ("David Raya", "Portero", 3, 0, "Convocado a la selección para este torneo."),
        ("Aymeric Laporte", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Robin Le Normand", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Fabián Ruiz", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Dani Olmo", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Álvaro Morata", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Ferran Torres", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Nico Williams", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
    ],
    "Inglaterra": [
        ("Jude Bellingham", "Mediocampista", 5, 3, "Uno de los mediocampistas más completos y jóvenes del fútbol mundial."),
        ("Harry Kane", "Delantero", 9, 5, "Máximo goleador histórico de la selección inglesa."),
        ("Phil Foden", "Mediocampista", 11, 2, "Formado desde niño en la academia del Manchester City."),
        ("Declan Rice", "Mediocampista", 4, 1, "Mediocampista defensivo, pieza clave en la recuperación de balón."),
        ("Jordan Pickford", "Portero", 1, 0, "Portero titular indiscutido de los últimos torneos ingleses."),
        ("Kyle Walker", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("John Stones", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Trent Alexander-Arnold", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Kobbie Mainoo", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Jordan Henderson", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Cole Palmer", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Bukayo Saka", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Marcus Rashford", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "México": [
        ("Santiago Giménez", "Delantero", 9, 4, "Delantero de gran instinto goleador, hijo del histórico 'Chaco' Giménez."),
        ("Edson Álvarez", "Mediocampista", 4, 1, "Capitán y pieza defensiva clave del mediocampo mexicano."),
        ("Julián Quiñones", "Delantero", 22, 2, "Delantero con gran capacidad de definición dentro del área."),
        ("Guillermo Ochoa", "Portero", 13, 0, "Portero histórico, presente en múltiples Copas del Mundo con México."),
        ("César Montes", "Defensa", 3, 0, "Central titular, pieza importante en la zaga tricolor."),
        ("Jesús Gallardo", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Julián Araujo", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Gerardo Arteaga", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Luis Chávez", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Carlos Rodríguez", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Orbelín Pineda", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Hirving Lozano", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Alexis Vega", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Estados Unidos": [
        ("Christian Pulisic", "Delantero", 10, 3, "Primer estadounidense en anotar en octavos de final de un Mundial."),
        ("Weston McKennie", "Mediocampista", 8, 1, "Mediocampista box-to-box con gran presencia física."),
        ("Folarin Balogun", "Delantero", 20, 2, "Delantero joven, referencia goleadora de la nueva generación."),
        ("Tyler Adams", "Mediocampista", 4, 0, "Capitán y mediocampista de gran despliegue defensivo."),
        ("Matt Turner", "Portero", 1, 0, "Portero titular, con experiencia en ligas europeas."),
        ("Tim Ream", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Chris Richards", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Antonee Robinson", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Yunus Musah", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Gio Reyna", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Brenden Aaronson", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Ricardo Pepi", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Sergiño Dest", "Defensa", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Italia": [
        ("Federico Chiesa", "Delantero", 14, 3, "Pieza clave en el título de la Eurocopa 2021 con Italia."),
        ("Nicolò Barella", "Mediocampista", 18, 1, "Mediocampista dinámico, motor del juego italiano."),
        ("Gianluigi Donnarumma", "Portero", 1, 0, "Uno de los porteros más jóvenes en debutar como titular en la Serie A."),
        ("Federico Dimarco", "Defensa", 32, 1, "Lateral ofensivo, pieza importante en la banda izquierda."),
        ("Sandro Tonali", "Mediocampista", 8, 0, "Mediocampista de buen despliegue y llegada al área."),
        ("Alessandro Bastoni", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Giovanni Di Lorenzo", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Riccardo Calafiori", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Davide Frattesi", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Nicolò Fagioli", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Giacomo Raspadori", "Delantero", 7, 0, "Convocado a la selección para este torneo."),
        ("Mateo Retegui", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Gianluca Scamacca", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
    ],
    "Portugal": [
        ("Cristiano Ronaldo", "Delantero", 7, 5, "Máximo goleador histórico del fútbol de selecciones a nivel mundial."),
        ("Bruno Fernandes", "Mediocampista", 8, 4, "Capitán y principal generador de juego de la selección portuguesa."),
        ("Rafael Leão", "Delantero", 17, 2, "Extremo veloz, campeón de la Serie A con el AC Milan."),
        ("Rúben Dias", "Defensa", 4, 0, "Central de gran jerarquía, pilar de la defensa portuguesa."),
        ("Diogo Costa", "Portero", 22, 0, "Portero titular, con gran seguridad bajo los tres palos."),
        ("Diogo Costa", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Pepe", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("João Cancelo", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Nuno Mendes", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Vitinha", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Bernardo Silva", "Mediocampista", 10, 0, "Convocado a la selección para este torneo."),
        ("William Carvalho", "Mediocampista", 11, 0, "Convocado a la selección para este torneo."),
        ("João Félix", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Países Bajos": [
        ("Cody Gakpo", "Delantero", 11, 3, "Máximo goleador neerlandés en el Mundial de Qatar 2022."),
        ("Xavi Simons", "Mediocampista", 10, 2, "Una de las mayores promesas del mediocampo europeo."),
        ("Virgil van Dijk", "Defensa", 4, 1, "Capitán y uno de los mejores centrales del mundo en su generación."),
        ("Memphis Depay", "Delantero", 9, 3, "Máximo goleador histórico de la selección neerlandesa."),
        ("Frenkie de Jong", "Mediocampista", 21, 0, "Mediocampista de gran salida de balón y visión de juego."),
        ("Justin Bijlow", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Nathan Aké", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Denzel Dumfries", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Jurriën Timber", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Teun Koopmeiners", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Tijjani Reijnders", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Steven Bergwijn", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Wout Weghorst", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Bélgica": [
        ("Kevin De Bruyne", "Mediocampista", 7, 2, "Considerado uno de los mejores mediocampistas creativos del mundo."),
        ("Romelu Lukaku", "Delantero", 9, 4, "Máximo goleador histórico de la selección belga."),
        ("Jérémy Doku", "Delantero", 11, 1, "Extremo explosivo, referente de la nueva generación belga."),
        ("Thibaut Courtois", "Portero", 1, 0, "Uno de los mejores porteros del mundo, ganador de múltiples títulos."),
        ("Youri Tielemans", "Mediocampista", 16, 1, "Mediocampista de buen pase y llegada al área rival."),
        ("Jan Vertonghen", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Toby Alderweireld", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Timothy Castagne", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Amadou Onana", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Arthur Theate", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Leandro Trossard", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Charles De Ketelaere", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Loïs Openda", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Croacia": [
        ("Luka Modrić", "Mediocampista", 10, 1, "Ganador del Balón de Oro 2018 tras llevar a Croacia a la final del Mundial."),
        ("Joško Gvardiol", "Defensa", 20, 1, "Uno de los defensas centrales más cotizados del fútbol europeo."),
        ("Ivan Perišić", "Delantero", 4, 2, "Veterano de gran jerarquía en ataque y banda izquierda."),
        ("Mateo Kovačić", "Mediocampista", 8, 0, "Mediocampista de gran técnica y manejo de balón."),
        ("Dominik Livaković", "Portero", 1, 0, "Portero titular, destacado en los penales del Mundial 2022."),
        ("Dominik Livaković", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Josip Stanišić", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Borna Sosa", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Josip Juranović", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Marcelo Brozović", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Luka Sučić", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Andrej Kramarić", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Bruno Petković", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Uruguay": [
        ("Darwin Núñez", "Delantero", 9, 4, "Delantero de gran potencia física y velocidad."),
        ("Federico Valverde", "Mediocampista", 15, 2, "Mediocampista box-to-box, pieza clave del Real Madrid."),
        ("Ronald Araújo", "Defensa", 4, 0, "Central de gran solidez defensiva y liderazgo en el campo."),
        ("Manuel Ugarte", "Mediocampista", 5, 0, "Mediocampista de contención, gran capacidad de recuperación."),
        ("Sergio Rochet", "Portero", 1, 0, "Portero titular de la 'Celeste' en los últimos años."),
        ("José María Giménez", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Mathías Olivera", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Guillermo Varela", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Rodrigo Bentancur", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Nahitan Nández", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Giorgian de Arrascaeta", "Mediocampista", 10, 0, "Convocado a la selección para este torneo."),
        ("Facundo Pellistri", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Maximiliano Araújo", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Colombia": [
        ("James Rodríguez", "Mediocampista", 10, 3, "Máximo goleador del Mundial de Brasil 2014 con seis anotaciones."),
        ("Luis Díaz", "Delantero", 7, 3, "Extremo veloz, referencia ofensiva del fútbol colombiano actual."),
        ("Jhon Durán", "Delantero", 9, 2, "Delantero joven con gran potencia física y de área."),
        ("David Ospina", "Portero", 1, 0, "Portero veterano, con amplia experiencia internacional."),
        ("Davinson Sánchez", "Defensa", 3, 0, "Central titular, pieza clave de la defensa cafetera."),
        ("Camilo Vargas", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Yerry Mina", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Daniel Muñoz", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Jefferson Lerma", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Richard Ríos", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Kevin Castaño", "Mediocampista", 11, 0, "Convocado a la selección para este torneo."),
        ("Jhon Arias", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Rafael Santos Borré", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Chile": [
        ("Alexis Sánchez", "Delantero", 7, 2, "Máximo goleador histórico de la selección chilena."),
        ("Arturo Vidal", "Mediocampista", 8, 1, "Mediocampista de garra, bicampeón de América con Chile."),
        ("Ben Brereton", "Delantero", 11, 1, "Delantero con gran capacidad de desmarque y remate."),
        ("Claudio Bravo", "Portero", 1, 0, "Portero veterano, referente histórico de 'La Roja'."),
        ("Gary Medel", "Defensa", 17, 0, "Central de gran carácter y liderazgo defensivo."),
        ("Mauricio Isla", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Guillermo Maripán", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Francisco Sierralta", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Charles Aránguiz", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Erick Pulgar", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Marcelino Núñez", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Eduardo Vargas", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Darío Osorio", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Japón": [
        ("Takefusa Kubo", "Delantero", 7, 2, "Formado en la academia del FC Barcelona, referente ofensivo asiático."),
        ("Kaoru Mitoma", "Delantero", 18, 2, "Extremo de gran regate, destacado en la Premier League."),
        ("Wataru Endo", "Mediocampista", 6, 0, "Capitán y pieza defensiva clave del mediocampo japonés."),
        ("Daichi Kamada", "Mediocampista", 10, 1, "Mediocampista ofensivo con buena llegada al área."),
        ("Ritsu Doan", "Delantero", 8, 2, "Extremo veloz, destacado en la Bundesliga alemana."),
        ("Shuichi Gonda", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Ko Itakura", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Yuto Nagatomo", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Takehiro Tomiyasu", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Hidemasa Morita", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Junya Ito", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Takumi Minamino", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Ayase Ueda", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Corea del Sur": [
        ("Son Heung-min", "Delantero", 7, 4, "Capitán y máximo goleador asiático en la historia de la Premier League."),
        ("Lee Kang-in", "Mediocampista", 18, 1, "Mediocampista creativo, una de las nuevas figuras del fútbol surcoreano."),
        ("Kim Min-jae", "Defensa", 3, 0, "Central sólido, apodado 'El Monstruo' por su dominio defensivo."),
        ("Lee Jae-sung", "Mediocampista", 14, 1, "Mediocampista de buen desmarque y llegada al área."),
        ("Kim Seung-gyu", "Portero", 1, 0, "Portero titular de la selección surcoreana."),
        ("Kim Young-gwon", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Kim Tae-hwan", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Kim Jin-su", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Hwang In-beom", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Paik Seung-ho", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Hwang Hee-chan", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Jo Gue-sung", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Oh Hyeon-gyu", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
    ],
    "Marruecos": [
        ("Achraf Hakimi", "Defensa", 2, 1, "Lateral ofensivo, pieza clave en la histórica semifinal de Qatar 2022."),
        ("Hakim Ziyech", "Mediocampista", 7, 2, "Mediocampista de gran calidad técnica y pase preciso."),
        ("Youssef En-Nesyri", "Delantero", 19, 3, "Delantero de gran juego aéreo y definición."),
        ("Yassine Bounou", "Portero", 1, 0, "Portero clave en la histórica campaña marroquí de Qatar 2022."),
        ("Sofyan Amrabat", "Mediocampista", 4, 0, "Mediocampista de contención, pieza defensiva fundamental."),
        ("Nayef Aguerd", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Romain Saïss", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Noussair Mazraoui", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Azzedine Ounahi", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Selim Amallah", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Abdelhamid Sabiri", "Mediocampista", 10, 0, "Convocado a la selección para este torneo."),
        ("Walid Cheddira", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Ilias Chair", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Senegal": [
        ("Sadio Mané", "Delantero", 10, 3, "Ganador de la Copa Africana de Naciones y referente ofensivo del continente."),
        ("Kalidou Koulibaly", "Defensa", 3, 0, "Capitán y uno de los centrales más sólidos de África."),
        ("Ismaïla Sarr", "Delantero", 18, 2, "Extremo veloz, pieza importante en el ataque senegalés."),
        ("Édouard Mendy", "Portero", 16, 0, "Portero campeón de Champions League con el Chelsea."),
        ("Nampalys Mendy", "Mediocampista", 5, 0, "Mediocampista de contención y buen posicionamiento."),
        ("Abdou Diallo", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Youssouf Sabaly", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Moussa Niakhaté", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Idrissa Gueye", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Cheikhou Kouyaté", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Pape Matar Sarr", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Boulaye Dia", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Habib Diallo", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Nigeria": [
        ("Victor Osimhen", "Delantero", 9, 4, "Ganador del premio al mejor jugador de la Serie A italiana."),
        ("Ademola Lookman", "Delantero", 8, 2, "Delantero de gran definición, destacado en Europa."),
        ("Alex Iwobi", "Mediocampista", 17, 1, "Mediocampista polivalente, nieto del histórico Jay-Jay Okocha."),
        ("William Troost-Ekong", "Defensa", 5, 0, "Capitán y central de experiencia en la selección nigeriana."),
        ("Wilfred Ndidi", "Mediocampista", 4, 0, "Mediocampista defensivo de gran capacidad de recuperación."),
        ("Stanley Nwabali", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Calvin Bassey", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Ola Aina", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Zaidu Sanusi", "Defensa", 7, 0, "Convocado a la selección para este torneo."),
        ("Frank Onyeka", "Mediocampista", 10, 0, "Convocado a la selección para este torneo."),
        ("Kelechi Iheanacho", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Samuel Chukwueze", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Moses Simon", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Ghana": [
        ("Mohammed Kudus", "Delantero", 20, 3, "Delantero de gran capacidad técnica y llegada al área."),
        ("Thomas Partey", "Mediocampista", 5, 0, "Mediocampista defensivo de gran despliegue físico."),
        ("Jordan Ayew", "Delantero", 9, 1, "Parte de una histórica familia futbolística ghanesa."),
        ("Mohammed Salisu", "Defensa", 12, 0, "Central titular, con experiencia en la Premier League."),
        ("Lawrence Ati-Zigi", "Portero", 1, 0, "Portero titular de las 'Estrellas Negras'."),
        ("Alexander Djiku", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Tariq Lamptey", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Joseph Aidoo", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Elisha Owusu", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Abdul Fatawu Issahaku", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("André Ayew", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Iñaki Williams", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Osman Bukari", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
    ],
    "Canadá": [
        ("Alphonso Davies", "Defensa", 19, 1, "Lateral izquierdo de gran velocidad, campeón de Champions League."),
        ("Jonathan David", "Delantero", 20, 3, "Máximo goleador de la nueva generación canadiense."),
        ("Cyle Larin", "Delantero", 17, 2, "Delantero histórico en la clasificación invicta de Canadá a Qatar 2022."),
        ("Stephen Eustáquio", "Mediocampista", 10, 1, "Mediocampista creativo, pieza clave del mediocampo canadiense."),
        ("Maxime Crépeau", "Portero", 1, 0, "Portero titular de la selección canadiense."),
        ("Milan Borjan", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Kamal Miller", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Alistair Johnston", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Richie Laryea", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Ismaël Koné", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Jonathan Osorio", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Tajon Buchanan", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Junior Hoilett", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
    ],
    "Costa Rica": [
        ("Keylor Navas", "Portero", 1, 0, "Ganador de tres Champions League consecutivas con el Real Madrid."),
        ("Joel Campbell", "Delantero", 12, 1, "Referente ofensivo en la histórica campaña de Brasil 2014."),
        ("Anthony Contreras", "Delantero", 21, 1, "Extremo joven, una de las nuevas caras del fútbol costarricense."),
        ("Francisco Calvo", "Defensa", 15, 0, "Central de experiencia, pieza clave de la 'Sele' tica."),
        ("Yeltsin Tejeda", "Mediocampista", 6, 0, "Mediocampista de contención con amplia trayectoria internacional."),
        ("Kendall Waston", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Ronald Matarrita", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Keysher Fuller", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Randall Leal", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Douglas López", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Alonso Martínez", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Warren Madrigal", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Aarón Suárez", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
    ],
    "Ecuador": [
        ("Moisés Caicedo", "Mediocampista", 23, 1, "Uno de los fichajes más caros del fútbol inglés en su posición."),
        ("Enner Valencia", "Delantero", 13, 3, "Máximo goleador histórico de la selección ecuatoriana en Mundiales."),
        ("Piero Hincapié", "Defensa", 3, 0, "Central joven con gran proyección en el fútbol europeo."),
        ("Pervis Estupiñán", "Defensa", 5, 1, "Lateral izquierdo de gran despliegue ofensivo."),
        ("Hernán Galíndez", "Portero", 1, 0, "Portero titular de 'La Tri' ecuatoriana."),
        ("Hernán Galíndez", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Félix Torres", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Willian Pacho", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Jhegson Méndez", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("José Cifuentes", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Alan Franco", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Ángel Mena", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Gonzalo Plata", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
    ],
    "Perú": [
        ("Gianluca Lapadula", "Delantero", 9, 2, "Delantero de gran instinto goleador dentro del área."),
        ("Christian Cueva", "Mediocampista", 20, 1, "Mediocampista creativo, referente de la 'Blanquirroja'."),
        ("Yoshimar Yotún", "Mediocampista", 19, 0, "Mediocampista de gran despliegue y recuperación."),
        ("Pedro Gallese", "Portero", 1, 0, "Portero titular histórico de la selección peruana."),
        ("Renato Tapia", "Mediocampista", 6, 0, "Mediocampista de contención, pieza defensiva del equipo."),
        ("Luis Advíncula", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Carlos Zambrano", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Anderson Santamaría", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Sergio Peña", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Pedro Aquino", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Edison Flores", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("André Carrillo", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
        ("Alex Valera", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
    ],
    "Paraguay": [
        ("Miguel Almirón", "Mediocampista", 10, 2, "Extremo veloz, destacado en la Premier League inglesa."),
        ("Julio Enciso", "Delantero", 18, 2, "Una de las jóvenes promesas más prometedoras de Paraguay."),
        ("Omar Alderete", "Defensa", 4, 0, "Central de gran solidez y buena salida con el balón."),
        ("Gustavo Gómez", "Defensa", 2, 0, "Capitán, central con amplia experiencia en el fútbol sudamericano."),
        ("Ángel Romero", "Delantero", 11, 1, "Delantero de experiencia, referente ofensivo paraguayo."),
        ("Fabián Balbuena", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Junior Alonso", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Alan Benítez", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Diego Gómez", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Robert Piris da Motta", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Ramón Sosa", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Antonio Sanabria", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
        ("Gustavo Velázquez", "Delantero", 13, 0, "Convocado a la selección para este torneo."),
    ],
    "Arabia Saudita": [
        ("Salem Al-Dawsari", "Delantero", 10, 2, "Autor del gol de la histórica victoria ante Argentina en 2022."),
        ("Firas Al-Buraikan", "Delantero", 9, 1, "Delantero referencia del fútbol saudí actual."),
        ("Saud Abdulhamid", "Defensa", 2, 0, "Lateral con gran proyección ofensiva."),
        ("Mohammed Al-Owais", "Portero", 21, 0, "Portero titular de la selección saudí."),
        ("Abdulelah Al-Malki", "Mediocampista", 15, 0, "Mediocampista de buen posicionamiento y recuperación."),
        ("Ali Al-Bulaihi", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Yasser Al-Shahrani", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Sultan Al-Ghannam", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Salman Al-Faraj", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Mohamed Kanno", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Nawaf Al-Abed", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Abdulrahman Ghareeb", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Hattan Bahebri", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Qatar": [
        ("Akram Afif", "Delantero", 7, 2, "Máxima figura y goleador del título de la Copa Asiática con Qatar."),
        ("Almoez Ali", "Delantero", 19, 3, "Máximo goleador histórico de la selección catarí."),
        ("Hassan Al-Haydos", "Mediocampista", 10, 0, "Capitán histórico y jugador con más partidos en la selección."),
        ("Saad Al-Sheeb", "Portero", 1, 0, "Portero titular, anfitrión del Mundial 2022."),
        ("Karim Boudiaf", "Mediocampista", 6, 0, "Mediocampista de experiencia en el fútbol catarí."),
        ("Khalid Muneer", "Portero", 2, 0, "Convocado a la selección para este torneo."),
        ("Bassam Al-Rawi", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Pedro Miguel", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Tarek Salman", "Defensa", 5, 0, "Convocado a la selección para este torneo."),
        ("Abdelkarim Hassan", "Defensa", 8, 0, "Convocado a la selección para este torneo."),
        ("Assim Madibo", "Mediocampista", 9, 0, "Convocado a la selección para este torneo."),
        ("Mohammed Waad", "Mediocampista", 11, 0, "Convocado a la selección para este torneo."),
        ("Homam Ahmed", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Australia": [
        ("Mathew Leckie", "Delantero", 7, 1, "Autor del gol de la clasificación a octavos de final en Qatar 2022."),
        ("Ajdin Hrustic", "Mediocampista", 19, 1, "Mediocampista creativo, pieza clave en el ataque australiano."),
        ("Craig Goodwin", "Delantero", 11, 1, "Extremo con gran despliegue por la banda izquierda."),
        ("Mathew Ryan", "Portero", 1, 0, "Portero titular histórico de los 'Socceroos'."),
        ("Aziz Behich", "Defensa", 16, 0, "Lateral izquierdo de experiencia internacional."),
        ("Harry Souttar", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Kye Rowles", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Nathaniel Atkinson", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Jackson Irvine", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Riley McGree", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Cameron Devlin", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Mitchell Duke", "Delantero", 9, 0, "Convocado a la selección para este torneo."),
        ("Martin Boyle", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
    ],
    "Dinamarca": [
        ("Christian Eriksen", "Mediocampista", 10, 2, "Regresó a la selección tras un histórico paro cardíaco en la Eurocopa 2021."),
        ("Rasmus Højlund", "Delantero", 9, 3, "Una de las jóvenes promesas del ataque danés en Europa."),
        ("Kasper Schmeichel", "Portero", 1, 0, "Hijo del legendario portero Peter Schmeichel."),
        ("Pierre-Emile Højbjerg", "Mediocampista", 23, 0, "Mediocampista defensivo, capitán en varios partidos."),
        ("Joakim Mæhle", "Defensa", 5, 1, "Lateral de gran proyección ofensiva."),
        ("Andreas Christensen", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Jannik Vestergaard", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Victor Kristiansen", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Rasmus Kristensen", "Defensa", 6, 0, "Convocado a la selección para este torneo."),
        ("Christian Nørgaard", "Mediocampista", 7, 0, "Convocado a la selección para este torneo."),
        ("Mikkel Damsgaard", "Mediocampista", 8, 0, "Convocado a la selección para este torneo."),
        ("Jonas Wind", "Delantero", 11, 0, "Convocado a la selección para este torneo."),
        ("Gustav Isaksen", "Delantero", 12, 0, "Convocado a la selección para este torneo."),
    ],
    "Polonia": [
        ("Robert Lewandowski", "Delantero", 9, 5, "Uno de los máximos goleadores en la historia del fútbol europeo."),
        ("Piotr Zieliński", "Mediocampista", 20, 1, "Mediocampista creativo, pieza clave del ataque polaco."),
        ("Wojciech Szczęsny", "Portero", 1, 0, "Portero titular histórico de la selección de Polonia."),
        ("Jakub Kiwior", "Defensa", 15, 0, "Central joven con experiencia en la Premier League."),
        ("Nicola Zalewski", "Mediocampista", 66, 0, "Extremo joven, pieza de la nueva generación polaca."),
        ("Bartosz Bereszyński", "Defensa", 2, 0, "Convocado a la selección para este torneo."),
        ("Matty Cash", "Defensa", 3, 0, "Convocado a la selección para este torneo."),
        ("Przemysław Frankowski", "Defensa", 4, 0, "Convocado a la selección para este torneo."),
        ("Sebastian Szymański", "Mediocampista", 5, 0, "Convocado a la selección para este torneo."),
        ("Jakub Moder", "Mediocampista", 6, 0, "Convocado a la selección para este torneo."),
        ("Krzysztof Piątek", "Delantero", 7, 0, "Convocado a la selección para este torneo."),
        ("Karol Świderski", "Delantero", 8, 0, "Convocado a la selección para este torneo."),
        ("Kamil Grosicki", "Delantero", 10, 0, "Convocado a la selección para este torneo."),
    ],
}

jugadores = []
for nombre_equipo, lista_jugadores in JUGADORES_DATA.items():
    id_equipo = mapa_equipos[nombre_equipo]
    for nombre, posicion, numero, goles, dato in lista_jugadores:
        jugadores.append({
            "nombre": nombre, "posicion": posicion, "numero": numero,
            "id_equipo": id_equipo, "goles": goles, "dato": dato,
        })
db.jugadores.insert_many(jugadores)

# ------------------ PARTIDOS (fase de grupos) ------------------
ahora = datetime.now()
fecha_base = ahora - timedelta(days=6)
partidos = []

CANALES_TV = [
    {"nombre": "TUDN", "color": "#ff0033"},
    {"nombre": "Televisa Deportes", "color": "#00a651"},
    {"nombre": "ESPN", "color": "#d5001c"},
    {"nombre": "Fox Sports", "color": "#003087"},
    {"nombre": "Amazon Prime Video", "color": "#00a8e1"},
    {"nombre": "Sky Sports", "color": "#0a1e3f"},
]

contador = 0
for grupo in grupos:
    parejas = [(grupo[0], grupo[1]), (grupo[2], grupo[3])]
    for local, visitante in parejas:
        fecha_partido = fecha_base + timedelta(days=contador * 2, hours=random.choice([12, 15, 18, 20]))
        ya_se_jugo = fecha_partido < ahora
        estado = "finalizados" if ya_se_jugo else "proximos"
        goles_local = random.randint(0, 3) if ya_se_jugo else 0
        goles_visitante = random.randint(0, 3) if ya_se_jugo else 0
        canal = random.choice(CANALES_TV)
        estadio_elegido = random.choice([e["estadio"] for e in equipos])

        partidos.append({
            "equipo_local": local, "equipo_visitante": visitante,
            "fecha": fecha_partido.strftime("%d %b %Y, %H:%M"),
            "estadio": estadio_elegido, "pais_sede": estadio_a_pais.get(estadio_elegido, ""),
            "canal_transmision": canal["nombre"], "canal_color": canal["color"],
            "goles_local": goles_local, "goles_visitante": goles_visitante, "estado": estado,
            "estadisticas": ([
                {"nombre": "Posesión", "valor": f"{random.randint(45,60)}% - {random.randint(40,55)}%"},
                {"nombre": "Tiros a puerta", "valor": f"{random.randint(3,14)} - {random.randint(3,14)}"},
            ] if estado == "finalizados" else []),
            "eventos": [],
        })
        contador += 1
db.partidos.insert_many(partidos)

# ------------------ NOTICIAS (con ícono temático, no foto genérica) ------------------
noticias = [
    {"titulo": "México presenta su tercer uniforme para el torneo", "fecha": "16 Sep 2026",
     "contenido": "El Tri reveló hoy la nueva playera alternativa inspirada en la cultura azteca.",
     "categoria": "destacadas", "icono": "jersey"},
    {"titulo": "FIFA confirma el calendario completo de Octavos de Final", "fecha": "15 Sep 2026",
     "contenido": "Se dieron a conocer sedes, fechas y horarios de la siguiente fase del torneo.",
     "categoria": "general", "icono": "calendario"},
    {"titulo": "Portugal golea en su debut con doblete de Cristiano Ronaldo", "fecha": "15 Sep 2026",
     "contenido": "El capitán luso abrió el marcador desde el punto penal en el minuto 12.",
     "categoria": "destacadas", "icono": "gol"},
    {"titulo": "Modrić: 'Este podría ser mi último Mundial'", "fecha": "14 Sep 2026",
     "contenido": "El mediocampista croata habló sobre el futuro de su carrera con la selección.",
     "categoria": "entrevistas", "icono": "entrevista"},
    {"titulo": "Sorpresa: Arabia Saudita golea en su debut", "fecha": "14 Sep 2026",
     "contenido": "El combinado saudí repite la hazaña de Qatar 2022 con un arranque contundente.",
     "categoria": "destacadas", "icono": "gol"},
    {"titulo": "Croacia confirma bajas por lesión antes del debut", "fecha": "13 Sep 2026",
     "contenido": "El cuerpo médico vatreni reportó dos ausencias sensibles para el primer partido.",
     "categoria": "general", "icono": "lesion"},
    {"titulo": "Lewandowski llega en su mejor forma física", "fecha": "13 Sep 2026",
     "contenido": "El delantero polaco aseguró sentirse listo para liderar el ataque de su selección.",
     "categoria": "entrevistas", "icono": "estrella"},
    {"titulo": 'Messi: "Nuestro objetivo es volver a hacer historia"', "fecha": "12 Sep 2026",
     "contenido": "El capitán argentino habló sobre las expectativas del equipo de cara al torneo.",
     "categoria": "entrevistas", "icono": "entrevista"},
    {"titulo": "Brasil presenta su nueva lista de convocados", "fecha": "12 Sep 2026",
     "contenido": "El cuerpo técnico brasileño confirmó a los jugadores que representarán al país.",
     "categoria": "fichajes", "icono": "plantilla"},
    {"titulo": "Inglaterra entrena con plantel completo", "fecha": "11 Sep 2026",
     "contenido": "Todos los convocados se reportaron sin lesiones antes del debut.",
     "categoria": "general", "icono": "plantilla"},
    {"titulo": "Mbappé, listo para liderar a Francia", "fecha": "11 Sep 2026",
     "contenido": "El delantero francés fue confirmado como capitán para este torneo.",
     "categoria": "destacadas", "icono": "estrella"},
    {"titulo": "Marruecos sueña con repetir su histórica actuación", "fecha": "10 Sep 2026",
     "contenido": "Los Leones del Atlas buscan volver a sorprender tras su semifinal de Qatar 2022.",
     "categoria": "general", "icono": "general"},
    {"titulo": "Japón y Corea del Sur, las apuestas fuertes de Asia", "fecha": "10 Sep 2026",
     "contenido": "Ambas selecciones llegan con planteles renovados y mucha ambición.",
     "categoria": "general", "icono": "general"},
]
db.noticias.insert_many(noticias)

# ------------------ ELIMINATORIAS (grupos + fase eliminatoria) ------------------
NOMBRES_GRUPOS = [f"Grupo {letra}" for letra in "ABCDEFGH"]
eliminatorias = []
for nombre_grupo, equipos_grupo in zip(NOMBRES_GRUPOS, grupos):
    eliminatorias.append({
        "nombre": nombre_grupo,
        "fase": "Fase de grupos",
        "descripcion": f"{nombre_grupo}, integrado por: {', '.join(equipos_grupo)}.",
        "fecha_inicio": "18 Jun 2027",
        "fecha_fin": "26 Jun 2027",
        "equipos_participantes": equipos_grupo,
    })

eliminatorias.append({
    "nombre": "Octavos de Final", "fase": "Eliminación directa",
    "descripcion": "Cruces entre los dos mejores de cada grupo.",
    "fecha_inicio": "30 Jun 2027", "fecha_fin": "3 Jul 2027", "equipos_participantes": [],
})
db.eliminatorias.insert_many(eliminatorias)

print(f"Listo: {len(equipos)} equipos, {len(jugadores)} jugadores, {len(partidos)} partidos, "
      f"{len(noticias)} noticias, {len(eliminatorias)} eliminatorias/grupos insertados correctamente.")
